### PR TITLE
Update hammerjs to use React.Component and react prop-types

### PR DESCRIPTION
**Pull request by chrisdoc**
This PR makes HammerJS compatibly with React 16 which removed `React.createClass`.

In order to make `npm run build` work I updated several dev dependencies and included babelify to transpile the ES6 class

### CODE REVIEW

**Comment by halkeye** [comment]
the other option is the polyfill - https://www.npmjs.com/package/create-react-class

i like your version better

**Comment by lostthetrail** [comment]
The package.json main attribute is no longer correct for node integrations, as node doesn't support the import/export syntax.

If you are transpiling down to 5.1, you could put those into a lib folder and then redirect the main attribute there.

**Comment by lostthetrail** [comment]
@chrisdoc Thanks for putting this PR in. Did you see my note about the package.json main attribute no longer being valid. This is interesting to me since I am doing some SSR and the file breaks NodeJS parsing due to the unexpected module syntax.

**Comment by chrisdoc** [comment]
@lostthetrail thank you for the feedback, I change it to use `import` and `export`. Can you also tell me how you are using it in combination with node? We do use SSR too but haven't tried it out with the updated version.

**Comment by lostthetrail** [comment]
@chrisdoc We server side render our react. In doing so, the whole module tree is loaded in Node. For Node to do this, it reads the required package.json main attribute to find more Node-compatible javascript to load. Currently, with your changes, the main attribute points to code that is not Node-compatible, due to, at least, the usage of `import` and `export`.

**Comment by halkeye** [comment]
As a work around you could use https://github.com/standard-things/esm/blob/master/README.md

**Comment by chrisdoc** [comment]
@lostthetrail you could use babel in the backend, how are transpiling JSX in node?

**Comment by JedWatson** [comment]
Thanks @chrisdoc and everyone for the review to get this ready for merge.

Sorry for the delay - I know this must have been frustrating, so thanks to the helpful twitter user who brought it to my attention.

I'll try and sort out the node version without breaking our ability to use import/export but otherwise it might be better to (in the short term) revert to `require` and `module.exports` for node compatibility then add es modules in a compatible way with a subsequent release.

Anyone have any strong preferences on that?

**Comment by oayres** [comment]
@JedWatson thinking for the many and not the few here: If somebody is using JSX on a Node server without transpilation, maybe we can just include a transpiled version in the npm module? More recent babel versions should assign the `export default` to `module.exports`.

So those that do not support import/export can just import it differently:
```
const Hammer = require('react-hammerjs/lib/es5')
```

Either way, getting it merged as-is will suffice!

**Comment by rhys-vdw** [comment]
@JedWatson Can we get a release please?

**Pull request merged**
