### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by pravindia**
Add support to react version 17

### CODE REVIEW

**Comment by scottrippey** [comment]
Fixes #102

**Comment by yashash-pugalia** [comment]
react18 too pls

**Comment by scottrippey** [comment]
Unfortunately, I had to abandon this package, in favor of `@use-gesture/react`.  I was hoping for some of hammer's extra gestures, but figured out how to make them work.

**Comment by cie** [comment]
https://www.npmjs.com/package/react-hammerjs-18 worked for me

**Pull request closed without merging**
